### ISSUE TITLE
Variable window resolution

### ISSUE THREAD

**Issue by bradbury** [sqrlab/RobotON#10]
Currently the Robot ON! game has a fixed resolution (1280x720). Need to modify game to support other resolutions.

**Comment by KashifIV** [comment]
- The side panel in game has been updated to handle multiple resolutions.

**Comment by KashifIV** [comment]
- Cinematic Sequence should be able to handle multiple resolutions. 
- Main Menu has groundwork for using Canvases.

**Comment by KashifIV** [comment]
The Game is now playable at every unity prepackaged resolution with the addition of 1920x1080 and 640x480. If adjustments need to be made the Camera2 script contains the adjustment in the start function. The left most area of the screen is found and the left position constant is set based on that.
