### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by bradbury** [sqrlab/RobotON#11]
Currently Robot ON! only compiled and tested on Windows and Mac. Need to generate a web version in Unity and test under multiple browsers (Chrome, IE, Firefox).

**Comment by Ibrahimmushtaq98** [comment]
Currently, the Web version requires a server that host the level files, which is done. It can only handle GET request at the moment. However, it will soon handle post.

**Comment by Ibrahimmushtaq98** [comment]
Web Version is now complete, it can do Get Request for files such as mp4, xml or text

**Comment by Ibrahimmushtaq98** [comment]
The current web version is not done. There are some web related performance issue and the issue related about video not being played on Mac specific OS

**Comment by Ibrahimmushtaq98** [comment]
Works properly yayayayay
