### ISSUE TITLE
Remote logging

### ISSUE THREAD

**Issue by bradbury** [sqrlab/RobotON#12]
Need to support remote logging prior to Fall 2019 study:

- server side logging + DB for storage of logs
- client side transmission of logs

Currently logs are collected and stored locally.

**Comment by KashifIV** [comment]
The Logger Class has been updated to provide a more comprehensive overview of how the player played the level.

**Comment by Ibrahimmushtaq98** [comment]
Currently, a Database is setup to handle RobotON, it isnt hard to implement the RobotBUG, will do it when I come back

**Comment by Ibrahimmushtaq98** [comment]
It is now done, it will capture the following data:

    name: {
        type: String,
        unique: true,
        required: 'Please Enter your name'
    },
    timeStarted: String,
    levels:[{
        name: String,
        time: String,
        progress: String,
        timeStarted: String,
        timeEnded: String,
        stars: String,
        points: String,
        tools :[{
            name: String,
            correctLine: String,
            reqTask: String,
            compTask: String,
            timeTool: String,
            lineUsed: String
        }],
        states :[{
            preEnergy: String,
            finEnergy: String,
            toolName: String,
            position: {
                line: String,
                x_pos: String,
                y_pos: String
            },
            progress: String,
            time: String,
            timestamp: String
        }],
        obstacal: [{
            name: String,
            line: String
        }],
        obstacalState: [{
            name: String,
            preEnergy: String,
            finEnergy: String,
            position: {
                line:String,
                x_pos:String,
                y_pos:String
            },
            timestamp: String
        }],
        enemy: [{
            name: String,
            preEenergy: String,
            finEnergy: String,
            movement: String,
            vision: String,

        }]
    }]

**Comment by Ibrahimmushtaq98** [comment]
I am reopening this issue due to the way that the logging is implemented. Currently there is remote logging, however, it works by sending a giant string to the DB. The string should be smaller, and every action should be sent to the DB rather then appending to the original string

**Comment by Ibrahimmushtaq98** [comment]
Now the game will send any update to the server rather than updating the string, then send that string to the server
