### ISSUE TITLE
Tutorial windows

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#166]
Disable prompt window buttons during tutorials
In tutorials where the demo requires use of prompt windows (e.g. activator tool), reveal buttons as they are needed and use the hand to demonstrate where/when to push the buttons

**Comment by KashifIV** [comment]
The hand will now indicate where to click when interacting with Question and Renamer objects. The OK button is disabled on all other prompts during tutorials.
