### ISSUE TITLE
Projectile GUI

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#167]
The hitbox for the throw button is small and not reliable; reduce the tendency to move the player instead of throwing the tool when the button is pressed, by enlarging the hitbox
Also increase transparency of the button so code can be seen through the animation

**Comment by KashifIV** [comment]
More preventive code has been added to ensure the player does not move unless the user clicks in the code region. The fire tool has also a bit of transparency, enough to see the code behind it.

**Comment by MichaelMiljanovic** [comment]
There still seems to be some issues with clicking the button, and clicking the sidebar also often causes involuntary movement

**Comment by KashifIV** [comment]
The code for detecting clicking has been redone to ensure involuntary movement.
