### ISSUE TITLE
Tool overhaul

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#180]
-eliminate cost of tool usage
-apply tool energy penalty only upon failed use of a tool. Start penalty at 50% (except bug fixer), and allow reduction of this number using progression mechanics (continue to. allow players to boost maximum energy as a separate upgrade). 
-modify bug fixer animation to emphasize dramatic effect + add suitable animation to the code upon failure
-add emphasis (animation or highlighting) to relevant game objects with active tool
--or dim non relevant game objects
-change commenter in robobug to toggler (a better name is desired)
-add additional incorrect comments to robot on
-add a step to commenter in robot on to prompt for correct/incorrect comments (i.e. on or off respectively). Should just be one keystroke/one tap.

**Comment by MichaelMiljanovic** [comment]
-add emphasis (animation or highlighting) to relevant game objects with active tool
--or dim non relevant game objects

**Comment by KashifIV** [comment]
Bug Commenter has been updated to Lock
Uncommenter has been updated to Reviewer 
All other tool updates have been added.
