### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#28]
-add comments to vague code blocks
-update headers with parameter descriptions
-remove useless methods and delete commented out code that won't be needed again
-improve code style (indenting, etc.)
-break down LevelGenerator wherever possible

**Comment by KashifIV** [comment]
I will give a brief description of the important the new classes added so far for reference. 

- **GlobalState** : It already sounds like bad practice but this static class focuses on data that is important for multiple scenes and maintains their state. Originally all files would have an instance of LevelGenerator to accomplish this but most classes no longer need an instance as they can use this class. 

- **Level** : This class is a data class storing the required pieces of data for LevelGenerator to function. Level comes with a **LevelFactory** to further simplify the process of taking the data from the XML. 

- **GameController** : This script can be found in the main camera of the game. It's goal is to take some responsibility from LevelGenerator in maintaining the Game aspects of the scene. Things such as winning, losing, picking which level to load. 

- **SidebarController, BackgroundControl, TimeDisplayController, etc.** : these scripts have been created/updated to handle more of their children as opposed to LevelGenerator trying to interface with all of them 1 to 1 enabling more decoupling. 

- **Tools** : Superclass for removing removing repetitive code found in line objects "wrapper", "breakpointer" etc. "comment" implementation still needs to be implemented

**Comment by KashifIV** [comment]
An Update on more fairly important classes during refactoring: 

- **LevelManager**: Maintains dynamic data used by Level Generator and facilitates in "managing" creating and destruction of Tool objects. The nature of LevelManager is that its operations are self contained and does not reference back to LevelGenerator. 

- **comment**: Comment has been refactored to be a super class for all the various types comments, and now inherits from **Tools**. See the issue regarding refactoring comment.cs for more info on the sub classes and their functions. 

- **ToolsFactory**: Creates Scripts and/or GameObjects of the tools needed using an xmlnode and line number. 

- **CommentTypeFactory**: Handles the differences in various kinds of comments in the game. Used only by *CommentFactory** 

- **CodeProperties** : Holds data regarding spacing, sizes and positioning of various code objects in the game.
