### ISSUE TITLE
Input Glitch

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#3]
Typing in "3." when the solution expects "3.0" for the checker does not seem to lead to either a correct or incorrect answer; no error message is given but the task is incomplete.

**Comment by acrodia** [comment]
Addressed with this bit of code here in question.cs:

![image](https://user-images.githubusercontent.com/4070334/44765691-e0e35500-ab23-11e8-87ce-a814fe2df57a.png)

**Comment by MichaelMiljanovic** [comment]
Issue resolved
