### ISSUE TITLE
Avatar selection

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#30]
Allow players to select from multiple different avatars (male, female, other)

**Comment by MichaelMiljanovic** [comment]
Some options:
https://opengameart.org/content/tux-junior-walking-sample
https://opengameart.org/content/fumiko-complete-charset
https://opengameart.org/content/lpc-sara
https://opengameart.org/content/the-robot-free-sprite
https://opengameart.org/content/ninja-adventure-free-sprite
https://opengameart.org/content/ninja-girl-free-sprite
https://opengameart.org/content/cat-dog-free-sprites
https://opengameart.org/content/adventurer-girl-free-sprite
https://opengameart.org/content/cute-girl-free-sprites
https://opengameart.org/content/the-boy-free-sprites

**Comment by KashifIV** [comment]
Added 3 new Characters: a Boy and a Girl and a new Robot to replace the pre-existing one. I'm still an advocate for Tux but maybe we can reopen the issue if we have time/ a need for him to be added!
