### ISSUE TITLE
Mouse Control

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#31]
Set up control so players can use mouse instead of keyboard (left click move, right click use tool, add button for changing tool)

**Comment by KashifIV** [comment]
- The Side panel in game is now hooked up with buttons, the onClick method has to be handled and they should be fine. 
- I have some ground work for the main menu to use buttons, I ditched it as it was getting fairly involved but please take a look at the disabled "MenuCanvas" object and their children. (when I make a pull request)

**Comment by KashifIV** [comment]
Added Mouse control capabilities. Code has been added to the question.cs class which required keyboard input for iOS and Android devices. This has yet to be tested but should be taken care of when porting to mobile devices. The majority of mouse capabilites can be found in the **Hero2Controller class**
