### ISSUE TITLE
GUIText Deprecation

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#33]
Getting warnings that the GUIText element is being removed; will need to make some adjustments to the menu and other objects to accommodate in case support is later removed completely.

**Comment by MichaelMiljanovic** [comment]
Same for GUI Texture elements

**Comment by KashifIV** [comment]
-Replaced all Legacy GUI components with updated Unity Text/Canvas/Images. 
-Some Resolution issues have been resolved. 
-Warnings still persist for older files, they will be taken care of when tackling the "Clean Repository" Issue
-A partial class of SelectTool has been made, this will be cleaned during refactoring.
