### ISSUE TITLE
Comment.cs split

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#36]
Comments, Uncomments, and incorrect versions of each are all jammed into a single class; this should be split into 4 different classes.

**Comment by KashifIV** [comment]
I have updated comment.cs to be an abstract super class of **IncorrectComment, CorrectComment, IncorrectUncomment and CorrectUncomment**. comment.cs also now inherits from Tools. Each of these classes override the **OnTriggerProtocol** and can optionally override **UpdateProtocol**. The ToolsFactory supports the creation of all of these types of comments with **CommentFactory** and **CommentTypeFactory** handles all the variations of comments.
