### ISSUE TITLE
Tool Use Visibility

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#4]
More obvious symbols should be used for tool tasks, and changed from 'broken' to 'fixed' after tools are used correctly.
![box_checker](https://cloud.githubusercontent.com/assets/3332190/19739476/10f5de04-9b89-11e6-8e29-e4cba0e5e88e.png)
![box_comment](https://cloud.githubusercontent.com/assets/3332190/19739477/13452822-9b89-11e6-81aa-705675c94f69.png)
![box_renamer](https://cloud.githubusercontent.com/assets/3332190/19739481/15890e0a-9b89-11e6-9c78-6a15a7c52359.png)
![box_uncomment](https://cloud.githubusercontent.com/assets/3332190/19739484/16e642fe-9b89-11e6-9682-4cbaaa4ad0b3.png)

**Comment by bradbury** [comment]
Scott -- this should be your top priority.

**Comment by MichaelMiljanovic** [comment]
Added to the most recent version!
