### ISSUE TITLE
Loading bar

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#41]
For the start of the game in particular

**Comment by KashifIV** [comment]
The start of the game shouldn't take too long anymore, however a loading bar might still be required between the transition from "Cinematic" and "newgame" scenes.

**Comment by KashifIV** [comment]
The "newgame" Audio has been removed from the game allowing for almost instant load time of the scene. A Loading bar won't be required ,if when we do add music, it is compressed.
