### ISSUE TITLE
Renaming inside lines

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#6]
Multiple errors occur when variable-color tags are used in the middle of a line, or when combined with other tags.

**Comment by MichaelMiljanovic** [comment]
Some examples to check-
Level 1-2: Commenting lines 7 and 11 does not change any colors
Level 4-2: Uncommenting lines 7 and 8 does not remove red coloring

**Comment by acrodia** [comment]
Similar issue on 4-3 with variable renamer for "A_CONSTANT"

**Comment by MichaelMiljanovic** [comment]
Resolved with improved Regex
