### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#60]
Stationary or Mobile (projectile launching) enemies that drain energy
Obstacles that dim/change code
Mobility changing obstacles (e.g. slowers, stickies)

**Comment by KashifIV** [comment]
An obstacle super class with a factory to create them has been added. The only obstacle in the game currently is a firewall. The XML input for the obstacle is similar to the bug. Obstacles begin being denoted with $O followed by the name of the name of the obstacle such as $OFirewall 20$. Parameters can be added like the 20, they are separated by space.
