### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#70]

**Comment by MichaelMiljanovic** [comment]
Query gamertag when new game is selected; allow mobile users to type in a text field

**Comment by Ibrahimmushtaq98** [comment]
Have an API setup such that when requested through /logsON or /logsBug followed by /leaderboard/levelname, it will return the a json which contains the name of the user, the level name, the points and the rank. This is all sorted, the next step is to send a request through unity and wait for a response, and using the UI that Khasif has made, pretty much inserting it to the leaderboard

**Comment by Ibrahimmushtaq98** [comment]
Leaderboard data has been set, however, currently we have points that are earned from the level, which is causing everyone earning the same points. Need to discuss what the leaderboard is actually showing

**Comment by Ibrahimmushtaq98** [comment]
Unfortunately due to how Unity Webgl was made, it is not possible to implement Mobile keyboard natively. Other people have made a "third party" fix, unfortunately, it doesn't work well with IOS. With this, ill be removing the feature and closing this, until Unity it self could fix this
