### ISSUE TITLE
Energy

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#75]
Introduce an energy meter that, when reduced to zero, causes the player to lose the game.

**Comment by KashifIV** [comment]
The game now shows an energy bar with an accompanying percent indicating the percent of energy left available to the user. The tools now show the consumption of energy as opposed to tool count, and you can no longer run out of a particular tool. However, the tool will disappear upon completion of a task. During the cinematic the user is shown how much their energy has increased by from completing the previous level.
