### ISSUE TITLE
Nonplayer Characters

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#79]
Introduce characters to aid the player during gameplay (e.g. personification of the prompt window, adding characters who give tools, etc.)

**Comment by KashifIV** [comment]
The Prompt window now has the robot showing up beside it to indicate speech. Later on, the remaining member of the group should be responsible for some dialog in the game play.

**Comment by KashifIV** [comment]
The boy and the girl now show up in game to talk the other through the level. The robot receives guidance from either the boy or girl randomly
