### ISSUE TITLE
Character Progression

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#80]
Add functionality to allow the player to improve their character over time (e.g. increased energy, movement speed, tool capacity, items for aiding against enemies and obstacles)

**Comment by KashifIV** [comment]
Character progression mechanics have been implemented in game however their values are up for change. StatLib.cs (values of the upgrades), CharacterStats.cs(what the player stores) and ProgresionPanel.cs (multiplier for cost of upgrades) are where you can manipulate these values.
